### ISSUE TITLE
Jetson Xavier AGX compatibility 

### ISSUE THREAD

**Issue by Jk7913** [barovehicles/lita-carrier-board#3]
Hi!

I'm interested in this board, would be possible to use it with Xavier AGX? 

Thanks.

**Comment by baroselfdriving** [comment]
> Hi!
> 
> 
> 
> I'm interested in this board, would be possible to use it with Xavier AGX? 
> 
> 
> 
> Thanks. 

Hi. Is compatible with Jetson Nano/Tx2 nx and Xavier Nx

We re in design process to manufacture the Agx and Orin version.

Best regards

Gabriel

**Comment by Jk7913** [comment]
Thank you for a quick answer. 
Best regards
